### ISSUE TITLE
我也在尝试使用CV技术写一个py的脚本。想参考一下你的思路。

### ISSUE THREAD

**Issue by maxi2015qwe** [dengqizhou30/AIAssistC#10]
你的图像分析是 通过截图的方式做的吗？
模型使用的是 YOLO模型吗？
你现在的帧数能到多少呢？

**Comment by dengqizhou30** [comment]
使用window api截图，模型尝试了mobilenet，现在改成efficientdet。一次处理耗时约50ms，大概20tps
