### ISSUE TITLE
我应该怎么使用该软件？

### ISSUE THREAD

**Issue by Caiyutao1997** [dengqizhou30/AIAssistC#15]
打开软件后点击开启图像检测就闪退。
我需要下载OpenCV和libtensorflow-gpu-windows还需要下载c++什么的吗？
OpenCV和libtensorflow-gpu-windows解压后我应该如何使用？

**Comment by dengqizhou30** [comment]
把dll拷贝到程序相同的目录试试。注意ibtensorflow-gpu要和你的显卡版本匹配。
