### ISSUE TITLE
开跟踪闪退

### ISSUE THREAD

**Issue by muconai** [dengqizhou30/AIAssistC#2]

**Comment by dengqizhou30** [comment]
要先手工安装鼠标键盘虚拟驱动，已经再工程readme文件中增加了说明，请参考。
https://github.com/dengqizhou30/AIAssistC

**Comment by muconai** [comment]
CPU占用好高，8700k一开屏幕检测就40

**Comment by muconai** [comment]
是不是可以优化下

**Comment by dengqizhou30** [comment]
AI模型推理默认开了多核，可以在代码中控制使用的CPU核数。降低cpu核数后带来的问题是检测速度变慢。正在尝试使用CUDA加速，成功后推理主要使用GPU，CPU使用率会降低。
