### ISSUE TITLE
我是个萌新

### ISSUE THREAD

**Issue by wanghong-111** [dengqizhou30/AIAssistC#9]
搞了下越搞越懵，有没有供菜鸡直接食用的方法，大佬，QQ及邮箱575850812@qq.com，跪求

**Comment by wanghong-111** [comment]
或者大佬说说从哪里入手，及需要学习哪些和学习路线，拜谢大佬。

**Comment by dengqizhou30** [comment]
执行依赖的opencv和tensorflow库太大，无法打包提供，目前只能自己编译，可以参考项目readme操作。
